// Hive Type IDs
const kUserProfileTypeId = 0;
const kMuscleGroupTypeId = 1;
const kExerciseTypeId = 2;
const kWeeklyPlanTypeId = 3;
const kWorkoutLogTypeId = 4;
const kWorkoutEntryTypeId = 5;
const kAppSettingsTypeId = 6;
const kStreakTypeId = 7;

// Hive Box Names
const kUserProfileBox = 'userProfile';
const kMuscleGroupsBox = 'muscleGroups';
const kExercisesBox = 'exercises';
const kWeeklyPlanBox = 'weeklyPlan';
const kWorkoutLogsBox = 'workoutLogs';
const kAppSettingsBox = 'appSettings';
const kStreaksBox = 'streaks';
const kWorkoutsBox = 'workouts';
